Repository typedb/typedb-benchmark, pull requests merged in 2020-12, with the labels that each got.

#97 Fixed simulation dependencies
  .grabl/automation.yml
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: bug

#100 Use remote builds
  .bazelrc
  .grabl/automation.yml
Labels: priority: high, type: build

#101 Send analysis name to grabl tracing
  SimulationRunner.java
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: refactor

#102 Fix simulation bugs
  .grabl/automation.yml
  SimulationRunner.java
  common/Simulation.java
  common/action/ActionFactory.java
  common/action/BUILD
  common/action/write/InsertTransactionAction.java
  common/agent/AgentFactory.java
  common/agent/BUILD
  common/agent/base/Agent.java
  common/agent/insight/ArbitraryOneHopAgent.java
  common/agent/insight/FindCurrentResidentsAgent.java
  common/agent/insight/FindLivedInAgent.java
  common/agent/insight/FindSpecificMarriageAgent.java
  common/agent/insight/FindSpecificPersonAgent.java
  common/agent/insight/FindTransactionCurrencyAgent.java
  common/agent/insight/FourHopAgent.java
  common/agent/insight/MeanWageAgent.java
  common/agent/insight/ThreeHopAgent.java
  common/agent/insight/TwoHopAgent.java
  common/agent/insight/WorldwideInsightAgent.java
  common/agent/region/CityAgent.java
  common/agent/region/ContinentAgent.java
  common/agent/region/CountryAgent.java
  common/agent/region/WorldAgent.java
  common/agent/write/AgeUpdateAgent.java
  common/agent/write/CompanyAgent.java
  common/agent/write/EmploymentAgent.java
  common/agent/write/FriendshipAgent.java
  common/agent/write/MarriageAgent.java
  common/agent/write/ParentshipAgent.java
  common/agent/write/PersonBirthAgent.java
  common/agent/write/ProductAgent.java
  common/agent/write/RelocationAgent.java
  common/agent/write/TransactionAgent.java
  common/driver/BUILD
  common/driver/TransactionalDbDriver.java
  common/utils/BUILD
  common/utils/Pair.java
  common/utils/Utils.java
  common/world/World.java
  config/config_test.yml
  dependencies/graknlabs/artifacts.bzl
  grakn/BUILD
  grakn/action/GraknActionFactory.java
  grakn/action/write/GraknInsertTransactionAction.java
  grakn/action/write/GraknUpdateAgesOfPeopleInCityAction.java
  grakn/driver/GraknOperation.java
  neo4j/BUILD
  neo4j/action/Neo4jActionFactory.java
  neo4j/action/write/Neo4jInsertTransactionAction.java
Labels: type: bug, type: refactor

#104 Various refactoring on simulation
  common/Simulation.java
  common/agent/base/Agent.java
  common/agent/base/SimulationContext.java
  common/agent/insight/WorldwideInsightAgent.java
  common/agent/region/CityAgent.java
  common/agent/region/ContinentAgent.java
  common/agent/region/CountryAgent.java
  common/agent/region/WorldAgent.java
  common/agent/write/AgeUpdateAgent.java
  common/agent/write/CompanyAgent.java
  common/agent/write/EmploymentAgent.java
  common/agent/write/FriendshipAgent.java
  common/agent/write/MarriageAgent.java
  common/agent/write/ParentshipAgent.java
  common/agent/write/PersonBirthAgent.java
  common/agent/write/ProductAgent.java
  common/agent/write/RelocationAgent.java
  common/agent/write/TransactionAgent.java
  common/driver/DbOperation.java
  common/driver/DbOperationFactory.java
  common/driver/LogWrapper.java
  common/driver/TransactionalDbOperation.java
  common/driver/TransactionalDbOperationFactory.java
  dependencies/graknlabs/artifacts.bzl
  grakn/action/write/GraknInsertPersonAction.java
  grakn/driver/GraknOperation.java
  grakn/driver/GraknOperationFactory.java
  neo4j/driver/Neo4jOperation.java
  neo4j/driver/Neo4jOperationFactory.java
Labels: type: refactor

#105 Remove low level traces
  .grabl/automation.yml
  grakn/driver/GraknDriver.java
  grakn/driver/GraknOperation.java
  neo4j/driver/Neo4jDriver.java
  neo4j/driver/Neo4jOperation.java
Labels: type: refactor

#106 Update all simulation jobs to long image variants
  .grabl/automation.yml
Labels: priority: blocker, type: build
