Repository typedb/typedb-benchmark, pull requests merged in 2021-01, with the labels that each got.

#107 Switch image back to default Ubuntu 20.04
  .grabl/automation.yml
Labels: type: build, type: refactor

#109 Update grabl automation yaml syntax
  .grabl/automation.yml
Labels: type: build

#110 Add Grakn Cluster benchmark
  .grabl/automation.yml
  BenchmarkRunner.java
  WORKSPACE
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  grakn/driver/GraknDriver.java
  test/BUILD
  test/BenchmarksForComparison.java
  test/ComparisonTest.java
  test/ComparisonTestSuite.java
Labels: type: feature
