Repository typedb/typedb-benchmark, pull requests merged in 2021-02, with the labels that each got.

#111 Fix waiting for Neo4J instance
  .grabl/automation.yml
Labels: priority: high, type: bug

#113 Fix neo4j startup
  .grabl/automation.yml
Labels: type: bug

#115 Add Grakn Cluster benchmark
  .grabl/automation.yml
  ci/BUILD
  ci/create-systemd-service.sh
  ci/install-ssh-credential.sh
  ci/systemd-service-template.txt
  ci/transfer-file.sh
  ci/wait-for-file.sh
  dependencies/graknlabs/artifacts.bzl
Labels: type: feature

#119 Enable correctness tests to ensure DB operations yield the same results
  .grabl/automation.yml
  grakn/action/insight/GraknArbitraryOneHopAction.java
  grakn/action/insight/GraknFindCurrentResidentsAction.java
  grakn/action/insight/GraknFindLivedInAction.java
  grakn/action/insight/GraknFindSpecificMarriageAction.java
  grakn/action/insight/GraknFindSpecificPersonAction.java
  grakn/action/insight/GraknFindTransactionCurrencyAction.java
  grakn/action/insight/GraknFourHopAction.java
  grakn/action/insight/GraknMeanWageOfPeopleInWorldAction.java
  grakn/action/insight/GraknThreeHopAction.java
  grakn/action/insight/GraknTwoHopAction.java
  grakn/action/read/GraknBirthsInCityAction.java
  grakn/action/read/GraknCitiesInContinentAction.java
  grakn/action/read/GraknCompaniesInContinentAction.java
  grakn/action/read/GraknCompaniesInCountryAction.java
  grakn/action/read/GraknMarriedCoupleAction.java
  grakn/action/read/GraknProductsInContinentAction.java
  grakn/action/read/GraknResidentsInCityAction.java
  grakn/action/read/GraknUnmarriedPeopleInCityAction.java
  grakn/action/write/GraknInsertCompanyAction.java
  grakn/action/write/GraknInsertEmploymentAction.java
  grakn/action/write/GraknInsertFriendshipAction.java
  grakn/action/write/GraknInsertMarriageAction.java
  grakn/action/write/GraknInsertParentShipAction.java
  grakn/action/write/GraknInsertPersonAction.java
  grakn/action/write/GraknInsertProductAction.java
  grakn/action/write/GraknInsertRelocationAction.java
  grakn/action/write/GraknInsertTransactionAction.java
  neo4j/Neo4JBenchmark.java
  neo4j/action/Model.java
  neo4j/action/Neo4jActionFactory.java
  neo4j/action/write/Neo4jInsertTransactionAction.java
  test/BUILD
  test/BenchmarksForComparison.java
  test/ComparisonTest.java
Labels: type: feature

#120 README section on differing counts between Grakn and Neo4j
  README.md
Labels: type: feature

#121 Refactor code to work with latest @graknlabs_dependencies
  .grabl/automation.yml
  WORKSPACE
  ci/BUILD
  ci/create-systemd-service.sh
  ci/install-ssh-credential.sh
  ci/systemd-service-template.txt
  ci/transfer-file.sh
  ci/wait-for-file.sh
  dependencies/graknlabs/repositories.bzl
Labels: type: build, type: refactor

#122 Use self-hosted Bazel cache
  .bazelrc
Labels: priority: high, type: build, type: feature
